name: RecipeAutoSync
main: io.github.recipesync.RecipeAutoSync
version: 1.2.0
api-version: 1.20
libraries:
  - io.papermc.paper:paper-api:1.20.6-R0.1-SNAPSHOT
softdepend:
  - Craftorithm
  - CMI
  - CustomCrafting
  - CustomRecipes
  - RecipeManager
